import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geostar } from "next/font/google";
import { ThemeProvider } from "~/components/ui/theme-provider"

export const metadata: Metadata = {
  title: "Joe's wonderful web",
  description: "Generated by Yours truly",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geostar = Geostar({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-geostar-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={geostar.variable}>
      <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
